
FROM golang:1.23-alpine AS builder


RUN apk add --no-cache gcc musl-dev

WORKDIR /app


COPY go.mod go.sum ./
RUN go mod download


COPY . .


ENV CGO_ENABLED=1
RUN go build -v -x -o t-queue-server .


FROM alpine:latest

WORKDIR /app


COPY --from=builder /app/t-queue-server .

COPY --from=builder /app/static ./static


EXPOSE 8080

CMD ["./t-queue-server"]
